apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name:  ms-api
        image: nginx:stable-alpine
        ports:
        - containerPort: 8282
